### ISSUE TITLE
Parameter parsing fails when 32 bit coil addresses are added to the LOG.SET - Python 3.11

### ISSUE THREAD

**Issue by mschlenstedt** [yozik04/nibe-mqtt#15]
Hi,

first of all: many thanks for this great piece of software!

I have a F1245 with an (I think) old firmware revision - my pump do not have the service menu 5.3.11 (modbus settings). So I cannot adjust wordswap in the service menu.

I use the latest NibeGW and get errors when reading 32 bit values. I tried to read "degree-minutes-32-bit-40940".

Output with setting "word_swap: true":
```
root@loxberrykeller:~# nibe-mqtt -c nibemqtt.yml
2022-11-28 08:48:15,295 - INFO     - Running Nibe MQTT 0.3.0 service with Nibe 1.3.0 lib
2022-11-28 08:48:15,355 - INFO     - Starting UDP server on port 9999
2022-11-28 08:48:15,362 - WARNING  - MQTT connected
2022-11-28 08:48:16,388 - INFO     - alarm-45001: 0
2022-11-28 08:48:16,390 - INFO     - bf1-ep14-flow-40072: 11.3
2022-11-28 08:48:16,392 - INFO     - brine-pump-state-ep14-43433: OFF
2022-11-28 08:48:16,394 - INFO     - compressor-state-ep14-43427: STOPPED
2022-11-28 08:48:16,395 - INFO     - cpr-status-ep14-43435: OFF
--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/nibe/connection/nibegw.py", line 188, in datagram_received
    self._on_raw_coil_value(row.coil_address, row.value)
  File "/usr/local/lib/python3.11/site-packages/nibe/connection/nibegw.py", line 383, in _on_raw_coil_value
    coil.value = self.coil_encoder.decode(coil, raw_value)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/nibe/connection/encoders.py", line 62, in decode
    value = self._get_parser(coil).parse(raw)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/construct/core.py", line 288, in parse
    return self.parse_stream(io.BytesIO(data), **contextkw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/construct/core.py", line 300, in parse_stream
    return self._parsereport(stream, context, "(parsing)")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/construct/core.py", line 312, in _parsereport
    obj = self._parse(stream, context, path)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/construct/core.py", line 1041, in _parse
    data = stream_read(stream, self.length, path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/construct/core.py", line 91, in stream_read
    raise StreamError("stream read less than specified amount, expected %d, found %d" % (length, len(data)), path=path)
construct.core.StreamError: Error in path (parsing)
stream read less than specified amount, expected 4, found 2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/logging/__init__.py", line 1110, in emit
    msg = self.format(record)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/logging/__init__.py", line 953, in format
    return fmt.format(record)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/logging/__init__.py", line 687, in format
    record.message = record.getMessage()
                     ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/logging/__init__.py", line 377, in getMessage
    msg = msg % self.args
          ~~~~^~~~~~~~~~~
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/local/bin/nibe-mqtt", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.11/site-packages/nibe_mqtt/console_scripts/nibe_mqtt_service.py", line 35, in main
    loop.run_forever()
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 604, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/usr/local/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.11/asyncio/selector_events.py", line 1161, in _read_ready
    self._protocol.datagram_received(data, addr)
  File "/usr/local/lib/python3.11/site-packages/nibe/connection/nibegw.py", line 220, in datagram_received
    logger.exception(
Message: "Unexpected exception during parsing packet data '5c00206850c9af0000889c7100a9a90a00a3a91400aba90000939c0000949c0000919c0000929c00008f9c0000909c00003ab95000ada94600a7a91400faa90200ffff0000ffff0000ffff0000ffff0000ffff0000cc' from ('192.168.3.230', 9999)"
Arguments: (StreamError('Error in path (parsing)\nstream read less than specified amount, expected 4, found 2'),)
^CTraceback (most recent call last):
  File "/usr/local/bin/nibe-mqtt", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/nibe_mqtt/console_scripts/nibe_mqtt_service.py", line 35, in main
    loop.run_forever()
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 604, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1873, in _run_once
    event_list = self._selector.select(timeout)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/selectors.py", line 468, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt

root@loxberrykeller:~#
```

And output with setting "word_swap: false":
```
root@loxberrykeller:~# nibe-mqtt -c nibemqtt.yml
2022-11-28 08:49:34,929 - INFO     - Running Nibe MQTT 0.3.0 service with Nibe 1.3.0 lib
2022-11-28 08:49:34,985 - INFO     - Starting UDP server on port 9999
2022-11-28 08:49:34,992 - WARNING  - MQTT connected
2022-11-28 08:49:35,406 - INFO     - alarm-45001: 0
2022-11-28 08:49:35,407 - INFO     - bf1-ep14-flow-40072: 11.3
2022-11-28 08:49:35,408 - INFO     - brine-pump-state-ep14-43433: OFF
2022-11-28 08:49:35,409 - INFO     - compressor-state-ep14-43427: STOPPED
2022-11-28 08:49:35,410 - INFO     - cpr-status-ep14-43435: OFF
--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/nibe/connection/nibegw.py", line 188, in datagram_received
    self._on_raw_coil_value(row.coil_address, row.value)
  File "/usr/local/lib/python3.11/site-packages/nibe/connection/nibegw.py", line 383, in _on_raw_coil_value
    coil.value = self.coil_encoder.decode(coil, raw_value)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/nibe/connection/encoders.py", line 62, in decode
    value = self._get_parser(coil).parse(raw)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/construct/core.py", line 288, in parse
    return self.parse_stream(io.BytesIO(data), **contextkw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/construct/core.py", line 300, in parse_stream
    return self._parsereport(stream, context, "(parsing)")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/construct/core.py", line 312, in _parsereport
    obj = self._parse(stream, context, path)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/construct/core.py", line 5101, in _parse
    data = stream_read(stream, self.decodeamount, path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/construct/core.py", line 91, in stream_read
    raise StreamError("stream read less than specified amount, expected %d, found %d" % (length, len(data)), path=path)
construct.core.StreamError: Error in path (parsing)
stream read less than specified amount, expected 4, found 2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/logging/__init__.py", line 1110, in emit
    msg = self.format(record)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/logging/__init__.py", line 953, in format
    return fmt.format(record)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/logging/__init__.py", line 687, in format
    record.message = record.getMessage()
                     ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/logging/__init__.py", line 377, in getMessage
    msg = msg % self.args
          ~~~~^~~~~~~~~~~
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/local/bin/nibe-mqtt", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.11/site-packages/nibe_mqtt/console_scripts/nibe_mqtt_service.py", line 35, in main
    loop.run_forever()
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 604, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/usr/local/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.11/asyncio/selector_events.py", line 1161, in _read_ready
    self._protocol.datagram_received(data, addr)
  File "/usr/local/lib/python3.11/site-packages/nibe/connection/nibegw.py", line 220, in datagram_received
    logger.exception(
Message: "Unexpected exception during parsing packet data '5c00206850c9af0000889c7100a9a90a00a3a91400aba90000939c0000949c0000919c0000929c00008f9c0000909c00003ab95000ada94600a7a91400faa90200ffff0000ffff0000ffff0000ffff0000ffff0000cc' from ('192.168.3.230', 9999)"
Arguments: (StreamError('Error in path (parsing)\nstream read less than specified amount, expected 4, found 2'),)
^CTraceback (most recent call last):
  File "/usr/local/bin/nibe-mqtt", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/nibe_mqtt/console_scripts/nibe_mqtt_service.py", line 35, in main
    loop.run_forever()
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 604, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1873, in _run_once
    event_list = self._selector.select(timeout)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/selectors.py", line 468, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt

root@loxberrykeller:~#
```

Full LOG.SET is:
```
[NIBL;20221128;8310]
Divisors		1	10	1	1	1	10	10	10	10	1	1	1	1
Date	Time	Alarm	BF1 EP14 Flow [l/m]	Brine Pump State EP14	Compressor State EP14	Cpr Status EP14	Degree Minutes (32 bit)	EB100-BE1 Current [A]	EB100-BE2 Current [A]	EB100-BE3 Current [A]	Speed brine pump [%]	Supply Pump Speed EP14 [%]	Supply Pump State EP14	EB100-EP14 PCA Base Relays
45001
40072
43433
43427
43435
40940
40083
40081
40079
47418
43437
43431
43514
```

Any help is highly appreciated.

**Comment by yozik04** [comment]
Why you do not want to upgrade firmware? It should be easy. At least it is very simple on F1255

**Comment by mschlenstedt** [comment]
Thanks @yozik04  for your fast reply! Well, I am just a little bit scared - my wife will kill me if for some reason the update will fail :-)

But if it's absolutely nessessary I will do it of course.

I just thought that it could be either "wordswap true" or "wordswap false". So one of the two settings should work from my point of view?

**Comment by yozik04** [comment]
I will try to investigate what is in the payload. Thank you for the report.

**Comment by yozik04** [comment]
> I just thought that it could be either "wordswap true" or "wordswap false". So one of the two settings should work from my point of view?

Yes. One of them should work in any case.

**Comment by mschlenstedt** [comment]
Ok, I upgraded the firmware to the latest version (v9.x) - and I also have now the service menu. But I think the problem is somewhere else. I still get the error - doen't matter what I choose for word_swap in the service menu and in the nibe-mqtt config. I tested all combinations - and all give the same error:

This is now the output with latest firmware:
```
root@loxberrykeller:~# vi nibemqtt.yml
root@loxberrykeller:~# nibe-mqtt -c nibemqtt.yml
2022-11-28 09:39:19,385 - INFO     - Running Nibe MQTT 0.3.0 service with Nibe 1.3.0 lib
2022-11-28 09:39:19,441 - INFO     - Starting UDP server on port 9999
2022-11-28 09:39:19,449 - WARNING  - MQTT connected
2022-11-28 09:39:21,178 - INFO     - alarm-45001: 0
2022-11-28 09:39:21,179 - INFO     - bf1-ep14-flow-40072: None
2022-11-28 09:39:21,180 - INFO     - brine-pump-state-ep14-43433: OFF
2022-11-28 09:39:21,181 - INFO     - compressor-state-ep14-43427: STOPPED
2022-11-28 09:39:21,182 - INFO     - cpr-status-ep14-43435: OFF
--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/nibe/connection/nibegw.py", line 188, in datagram_received
    self._on_raw_coil_value(row.coil_address, row.value)
  File "/usr/local/lib/python3.11/site-packages/nibe/connection/nibegw.py", line 383, in _on_raw_coil_value
    coil.value = self.coil_encoder.decode(coil, raw_value)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/nibe/connection/encoders.py", line 62, in decode
    value = self._get_parser(coil).parse(raw)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/construct/core.py", line 288, in parse
    return self.parse_stream(io.BytesIO(data), **contextkw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/construct/core.py", line 300, in parse_stream
    return self._parsereport(stream, context, "(parsing)")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/construct/core.py", line 312, in _parsereport
    obj = self._parse(stream, context, path)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/construct/core.py", line 1041, in _parse
    data = stream_read(stream, self.length, path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/construct/core.py", line 91, in stream_read
    raise StreamError("stream read less than specified amount, expected %d, found %d" % (length, len(data)), path=path)
construct.core.StreamError: Error in path (parsing)
stream read less than specified amount, expected 4, found 2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/logging/__init__.py", line 1110, in emit
    msg = self.format(record)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/logging/__init__.py", line 953, in format
    return fmt.format(record)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/logging/__init__.py", line 687, in format
    record.message = record.getMessage()
                     ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/logging/__init__.py", line 377, in getMessage
    msg = msg % self.args
          ~~~~^~~~~~~~~~~
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/local/bin/nibe-mqtt", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.11/site-packages/nibe_mqtt/console_scripts/nibe_mqtt_service.py", line 35, in main
    loop.run_forever()
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 604, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/usr/local/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.11/asyncio/selector_events.py", line 1161, in _read_ready
    self._protocol.datagram_received(data, addr)
  File "/usr/local/lib/python3.11/site-packages/nibe/connection/nibegw.py", line 220, in datagram_received
    logger.exception(
Message: "Unexpected exception during parsing packet data '5c00206850c9af0000889c0080a9a90a00a3a91400aba90000939c0000949c0000919c0000929c00008f9c0000909c00003ab95000ada96400a7a95000faa90200ffff0000ffff0000ffff0000ffff0000ffff00005b' from ('192.168.3.230', 9999)"
Arguments: (StreamError('Error in path (parsing)\nstream read less than specified amount, expected 4, found 2'),)
^CTraceback (most recent call last):
  File "/usr/local/bin/nibe-mqtt", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/nibe_mqtt/console_scripts/nibe_mqtt_service.py", line 35, in main
    loop.run_forever()
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 604, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1873, in _run_once
    event_list = self._selector.select(timeout)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/selectors.py", line 468, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt

root@loxberrykeller:~#
```

**Comment by mschlenstedt** [comment]
If you need a tcpdump or something else please just let me know.

**Comment by yozik04** [comment]
you have provided packet data. this is sufficient for initial investigation.

**Comment by mschlenstedt** [comment]
I now removed all values from LOG.SET except of "alarm-45001" and this works fine for the moment. So maybe there was a problem with the originally included values/data.

**Comment by yozik04** [comment]
ok, I understand the problem... 32bit values are not supported in LOG.SET yet. because these do not fit =)

**Comment by yozik04** [comment]
Most probably it fails on 40083. Log output should be definitely better.

**Comment by yozik04** [comment]
40083, 40081, 40079 are unsigned 32 bit registers.

**Comment by yozik04** [comment]
Fixed in lib version 1.3.1

**Comment by mschlenstedt** [comment]
I will test this evening. Thanks a lot!

**Comment by mschlenstedt** [comment]
I upgraded to 0.3.1 and use this LOG:SET:

```
[NIBL;20221201;8310]
Divisors		10	1	1	1	1	1	10	1	1
Date	Time	BT1 Outdoor Temperature [°C]	Alarm	Brine Pump State EP14	Compressor State EP14	Supply Pump Speed EP14 [%]	Supply Pump State EP14	Degree Minutes (32 bit)	PCA-Power Relays EP14	EB100-EP14 PCA Base Relays
40004
45001
43433
43427
43437
43431
40940
43516
43514
```

Output of nibe-mqtt is:

```
2022-12-01 18:18:22,410 - INFO     - alarm-45001: 0
2022-12-01 18:18:22,410 - INFO     - brine-pump-state-ep14-43433: OFF
2022-12-01 18:18:22,411 - INFO     - compressor-state-ep14-43427: STOPPED
2022-12-01 18:18:22,411 - INFO     - supply-pump-speed-ep14-43437: 70
2022-12-01 18:18:22,411 - INFO     - supply-pump-state-ep14-43431: ON
2022-12-01 18:18:22,411 - WARNING  - Ignoring coil 40940 value 0000 - failed to decode
2022-12-01 18:18:22,412 - WARNING  - Ignoring coil 40941 value 0000 - coil definition not found
2022-12-01 18:18:22,412 - INFO     - pca-power-relays-ep14-43516: 0
2022-12-01 18:18:22,412 - INFO     - eb100-ep14-pca-base-relays-43514: 2
```
Note that I have 40941 not in my LOG.SET. and 40940 is degree_minutes (32bit).

**Comment by yozik04** [comment]
turn on debug. you can see that packet actually had 40941 in response

**Comment by yozik04** [comment]
40940 is ignored, because 32-bit value can not fit into 16-bit space. Or maybe Nibe encodes 32-bit this way....

**Comment by mschlenstedt** [comment]
Ok, I understand. So it seems to work ;-) Thanks a lot! I will close this issue as fixed.

Thanks again1
