### ISSUE TITLE
is my heat pump supported ?

### ISSUE THREAD

**Issue by ThomasHpc** [yozik04/nibe-mqtt#23]
Hello,

I get some errors when running the script, maybe my Nibe SHK200M is not supported.

This is from terminal window:

thomas@raspberrypi:~ $ nibe-mqtt -c /home/thomas/config.yaml
2023-05-28 14:40:55,127 - INFO     - MainThread - root - Running Nibe MQTT 0.4.0 service with Nibe 2.2.0 lib
2023-05-28 14:40:55,467 - INFO     - MainThread - nibe.nibe.connection.nibegw - Starting UDP server on port 9999
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/nibe/connection/nibegw.py", line 160, in start
    sock.bind(sockaddr)
OSError: [Errno 98] Address already in use

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/nibe-mqtt", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/nibe_mqtt/console_scripts/nibe_mqtt_service.py", line 34, in main
    loop.run_until_complete(service.start())
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/dist-packages/nibe_mqtt/service.py", line 108, in start
    await self.connection.start()
  File "/usr/local/lib/python3.9/dist-packages/nibe/connection/nibegw.py", line 165, in start
    raise AddressInUseException(f"Address in use {sockaddr}")
nibe.exceptions.AddressInUseException: Address in use ('0.0.0.0', 9999)
thomas@raspberrypi:~ $

**Comment by yozik04** [comment]
Address already in use. Some other program uses the port.

**Comment by ThomasHpc** [comment]
I got it up running now with root access, but the heat pump status indicator goes red now, and no data is received.
In the config.yaml i set model as SMO40 which is the hardware in my heat pump , but the actual model name is SHK200M. Can anything be changed so that the software can recognize my heat pump? This is what the log from the USB on the heat pump:

Divisors		1	1	10	10	10	10	10	10	1	10	1	10	10	10	1	1	10	1	1	1	1	10	10	10	10	10	10	10	10	10	10	1
Date	Time	version(43001)	R-version(44331)	BT1(40004)	BT6(40014)	BT7(40013)	BT25(40071)	BT71(40152)	BT63(40121)	Add.Step(43091)	EP14-BF1 (40072)	Alarm number(45001)	Calc. Supply(43009)	Degree Minutes(40940)	BT1-Average(40067)	Relays PCA-Base(43514)	compr. freq. calc(44775)	compr. freq. act(44701)	compr. state(44457)	compr. protection mode(44702)	GP12-speed(44396)	GP10-on/off(43189)	EB101-BT3(44055)	EB101-BT12(44058)	EB101-BT14(44059)	EB101-BT15(44060)	EB101-BT16(44363)	EB101-BT28(44362)	EB101-BP4(44699)	EB101-BP4-raw(44698)	Saturation temp.(34000)	Sat. temp. sent(34001)	Prio(43086)
2023-02-23	21:47:07	9542	4	19	118	435	255	238	255	0	145	251	250	-1143	24	6	25	350	1	0	50	1	241	259	290	242	-8	16	164	384	99	99	30

**Comment by yozik04** [comment]
Something is wrong with your nibegw. It should respond properly to the pump so it won't go into failed state.

**Comment by ThomasHpc** [comment]
So it doesn't matter that the heat pump controller hardware not is SMO40 but is a SHK200M ?

**Comment by yozik04** [comment]
Before running nibe-mqtt you need to make NibeGW stable so the pump won't go to alarm state. Next step will be already nibe-mqtt.
I really doubt that Nibe has a different protocol for your model.
Can it be that your model has TCP Modbus as S series pumps?
