### ISSUE TITLE
paho_mqtt in requirements.txt not limited to Version 1.x. Breaking changes in 2.x.

### ISSUE THREAD

**Issue by ErikOlufson** [yozik04/nibe-mqtt#25]
Hi,

in mqtt.py paho.mqtt.client is used.

In requirements.txt paho_mqtt is setup with > 1.5.0.

But, since paho_mqtt 2.0 got released some breaking changes were made. Including the client.

`
Traceback (most recent call last):
  File "/usr/local/bin/nibe-mqtt", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/nibe_mqtt/console_scripts/nibe_mqtt_service.py", line 27, in main
    service = Service(conf)
              ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/nibe_mqtt/service.py", line 39, in __init__
    self.mqtt_client = MqttConnection(self, conf["mqtt"])
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/nibe_mqtt/mqtt.py", line 31, in __init__
    self._client = Client(
                   ^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/paho/mqtt/client.py", line 766, in __init__
    raise ValueError(
ValueError: Unsupported callback API version: version 2.0 added a callback_api_version, see migrations.md for details
`

Maybe it would be a good thing to add "<1.6.x" in requirements.txt or migrate to 2.x ?

What do you thing.

Have a nice weekend!

**Comment by yozik04** [comment]
Thank you for the info

**Comment by yozik04** [comment]
You can use https://github.com/yozik04/nibe-mqtt/releases/tag/0.5.1 now.
