### ISSUE TITLE
address/coil ist for vvm500

### ISSUE THREAD

**Issue by frank8the9tank** [yozik04/nibe-mqtt#7]
I have the integration/add-on working, so many thanks.!!!!!

I'm looking for a address list/ coil list for the VVM500
If there is a address in the list that's not known i get an error and the add-on stops,
So i need to known what addresses i can use, where can i see this?
40033 and 40004 are working.

My config is following:
logging:
  level: WARNING
  format: "%(asctime)s - %(levelname)-8s - %(threadName)-10s - %(name)s - %(message)s"
mqtt:
  host: 192.168.4.18
  protocol: 5
  username: mqttuser
  password: q~18Ax76gK!!apa4
nibe:
  model: VVM500
  nibegw:
    ip: 192.168.4.53
    listening_port: 9999
    read_port: 10000
    write_port: 10001
  poll:
    interval: 30
    coils:
      - bt50-room-temp-s1-40033
      - bt1-outdoor-temperature-40004

**Comment by frank8the9tank** [comment]
I get this in the log from the add-on:
```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/nibe/heatpump.py", line 135, in get_coil_by_name
    return self._name_to_coil[str(name)]
KeyError: 'compressor-frequency-actual-43136'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/bin/nibe-mqtt", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.10/site-packages/nibe_mqtt/console_scripts/nibe_mqtt_service.py", line 26, in main
    service = Service(conf)
  File "/usr/lib/python3.10/site-packages/nibe_mqtt/service.py", line 40, in __init__
    self.poller = PollService(self, poll_config)
  File "/usr/lib/python3.10/site-packages/nibe_mqtt/service.py", line 147, in __init__
    self._coils = [self._get_coil(key) for key in conf["coils"]]
  File "/usr/lib/python3.10/site-packages/nibe_mqtt/service.py", line 147, in <listcomp>
    self._coils = [self._get_coil(key) for key in conf["coils"]]
  File "/usr/lib/python3.10/site-packages/nibe_mqtt/service.py", line 151, in _get_coil
    return self._heatpump.get_coil_by_name(name_or_address)
  File "/usr/lib/python3.10/site-packages/nibe/heatpump.py", line 137, in get_coil_by_name
    raise CoilNotFoundException(f"Coil with name '{name}' not found")
nibe.exceptions.CoilNotFoundException: Coil with name 'compressor-frequency-actual-43136' not found
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

**Comment by frank8the9tank** [comment]
is also have in the log from the add-on:

```
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/nibe/connection/nibegw.py", line 103, in datagram_received
    msg = Response.parse(data)
  File "/usr/lib/python3.10/site-packages/construct/core.py", line 288, in parse
    return self.parse_stream(io.BytesIO(data), **contextkw)
  File "/usr/lib/python3.10/site-packages/construct/core.py", line 300, in parse_stream
    return self._parsereport(stream, context, "(parsing)")
  File "/usr/lib/python3.10/site-packages/construct/core.py", line 312, in _parsereport
    obj = self._parse(stream, context, path)
  File "/usr/lib/python3.10/site-packages/construct/core.py", line 787, in _parse
    return self.parsefunc(stream, context)
  File "", line 62, in parseall
  File "", line 31, in parse_struct_1
  File "", line 21, in parse_const
construct.core.ConstError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/bin/nibe-mqtt", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.10/site-packages/nibe_mqtt/console_scripts/nibe_mqtt_service.py", line 32, in main
    loop.run_forever()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 600, in run_forever
    self._run_once()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1896, in _run_once
    handle._run()
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/lib/python3.10/asyncio/selector_events.py", line 1027, in _read_ready
    self._protocol.datagram_received(data, addr)
  File "/usr/lib/python3.10/site-packages/nibe/connection/nibegw.py", line 139, in datagram_received
    logger.exception(
Message: "Unexpected exception during parsing packet data 'b'd0f281f88bff9af7d5ef94b6d1b4c09fec95e68fe187e8caf08bf68ba785e08de89cf98ba993e8caadc8bce391f495f98de489eccef48ff28ff2'' from ('172.30.32.1', 46983)"
Arguments: (ConstError(''),)
```

**Comment by yozik04** [comment]
Hi, list is here for your model: https://github.com/yozik04/nibe/blob/master/nibe/data/vvm310_vvm500.json

**Comment by frank8the9tank** [comment]
Yes, many thanks! that really helps!
What do you think about the above error logs?

**Comment by yozik04** [comment]
Did we resolve your problem? Or you just closed regardless of result?

**Comment by frank8the9tank** [comment]
For me the problem was solved,
But i no longer use this method for my nibe unit,
There is now an official integration in HA for this, so you only need the nibeGW for implementation.

**Comment by yozik04** [comment]
Official method uses the same library. So what you experiencing in mqtt you would experience in official as well. :)
